services:
    pe_licensing.object_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        arguments:
            - '%pe_licensing.object_manager_name%'

    pe_licensing.repository.license.default:
        class: PE\Bundle\LicensingBundle\Doctrine\LicenseRepository
        arguments:
            - '@pe_licensing.object_manager'
            - '%pe_licensing.class.license%'

    pe_licensing.manager.default:
        public: true
        class: PE\Bundle\LicensingBundle\Manager\LicensingManager
        arguments:
            - '@pe_licensing.repository.license'

    pe_licensing.server:
        public: true
        class: PE\Bundle\LicensingBundle\Server\Server
        arguments:
            - '@pe_licensing.repository.license'

    pe_licensing.client.config:
        public: true
        class: PE\Bundle\LicensingBundle\Client\ClientConfig
        arguments: [~, ~, ~, ~] # Arguments processed in extension

    pe_licensing.client.http:
        class: GuzzleHttp\Client

    pe_licensing.client:
        public: true
        class: PE\Bundle\LicensingBundle\Client\Client
        arguments:
            - '@pe_licensing.client.config'
            - '@cache.app'
            - '@pe_licensing.client.http'
