parameters:
    pe_licensing.server_key: ~

services:
    pe_licensing.object_manager:
        class: Doctrine\Common\Persistence\ObjectManager
        arguments:
            - '%pe_licensing.object_manager_name%'

    pe_licensing.repository.license.default:
        class: PE\Bundle\LicensingBundle\Doctrine\LicenseRepository
        arguments:
            - '@pe_licensing.object_manager'
            - '%pe_licensing.class.license%'

    pe_licensing.server.default:
        public: true
        class: PE\Component\Licensing\Server\Server
        arguments:
            - '@pe_licensing.repository.license'
            - ~

    pe_licensing.client.http:
        class: GuzzleHttp\Client

    pe_licensing.client.default:
        public: true
        class: PE\Component\Licensing\Client\Client
        arguments:
            - '@pe_licensing.client.http'
            - ~
            - ~
            - '@cache.app'
            - ~

    pe_licensing.controller.server:
        public: true
        class: PE\Bundle\LicensingBundle\Controller\ServerController
        arguments: ['@pe_licensing.server']